/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SeniorRecordImport } from './routes/senior.record'
import { Route as SeniorMemoriesImport } from './routes/senior.memories'
import { Route as CaregiverReportImport } from './routes/caregiver.report'
import { Route as CaregiverRecordImport } from './routes/caregiver.record'
import { Route as CaregiverReadyImport } from './routes/caregiver.ready'
import { Route as CaregiverCreateImport } from './routes/caregiver.create'
import { Route as CaregiverActivityImport } from './routes/caregiver.activity'

// Create Virtual Routes

const SeniorHomeLazyImport = createFileRoute('/senior/home')()
const CaregiverHomeLazyImport = createFileRoute('/caregiver/home')()

// Create/Update Routes

const SeniorHomeLazyRoute = SeniorHomeLazyImport.update({
  id: '/senior/home',
  path: '/senior/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/senior.home.lazy').then((d) => d.Route))

const CaregiverHomeLazyRoute = CaregiverHomeLazyImport.update({
  id: '/caregiver/home',
  path: '/caregiver/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/caregiver.home.lazy').then((d) => d.Route),
)

const SeniorRecordRoute = SeniorRecordImport.update({
  id: '/senior/record',
  path: '/senior/record',
  getParentRoute: () => rootRoute,
} as any)

const SeniorMemoriesRoute = SeniorMemoriesImport.update({
  id: '/senior/memories',
  path: '/senior/memories',
  getParentRoute: () => rootRoute,
} as any)

const CaregiverReportRoute = CaregiverReportImport.update({
  id: '/caregiver/report',
  path: '/caregiver/report',
  getParentRoute: () => rootRoute,
} as any)

const CaregiverRecordRoute = CaregiverRecordImport.update({
  id: '/caregiver/record',
  path: '/caregiver/record',
  getParentRoute: () => rootRoute,
} as any)

const CaregiverReadyRoute = CaregiverReadyImport.update({
  id: '/caregiver/ready',
  path: '/caregiver/ready',
  getParentRoute: () => rootRoute,
} as any)

const CaregiverCreateRoute = CaregiverCreateImport.update({
  id: '/caregiver/create',
  path: '/caregiver/create',
  getParentRoute: () => rootRoute,
} as any)

const CaregiverActivityRoute = CaregiverActivityImport.update({
  id: '/caregiver/activity',
  path: '/caregiver/activity',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/caregiver/activity': {
      id: '/caregiver/activity'
      path: '/caregiver/activity'
      fullPath: '/caregiver/activity'
      preLoaderRoute: typeof CaregiverActivityImport
      parentRoute: typeof rootRoute
    }
    '/caregiver/create': {
      id: '/caregiver/create'
      path: '/caregiver/create'
      fullPath: '/caregiver/create'
      preLoaderRoute: typeof CaregiverCreateImport
      parentRoute: typeof rootRoute
    }
    '/caregiver/ready': {
      id: '/caregiver/ready'
      path: '/caregiver/ready'
      fullPath: '/caregiver/ready'
      preLoaderRoute: typeof CaregiverReadyImport
      parentRoute: typeof rootRoute
    }
    '/caregiver/record': {
      id: '/caregiver/record'
      path: '/caregiver/record'
      fullPath: '/caregiver/record'
      preLoaderRoute: typeof CaregiverRecordImport
      parentRoute: typeof rootRoute
    }
    '/caregiver/report': {
      id: '/caregiver/report'
      path: '/caregiver/report'
      fullPath: '/caregiver/report'
      preLoaderRoute: typeof CaregiverReportImport
      parentRoute: typeof rootRoute
    }
    '/senior/memories': {
      id: '/senior/memories'
      path: '/senior/memories'
      fullPath: '/senior/memories'
      preLoaderRoute: typeof SeniorMemoriesImport
      parentRoute: typeof rootRoute
    }
    '/senior/record': {
      id: '/senior/record'
      path: '/senior/record'
      fullPath: '/senior/record'
      preLoaderRoute: typeof SeniorRecordImport
      parentRoute: typeof rootRoute
    }
    '/caregiver/home': {
      id: '/caregiver/home'
      path: '/caregiver/home'
      fullPath: '/caregiver/home'
      preLoaderRoute: typeof CaregiverHomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/senior/home': {
      id: '/senior/home'
      path: '/senior/home'
      fullPath: '/senior/home'
      preLoaderRoute: typeof SeniorHomeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/caregiver/activity': typeof CaregiverActivityRoute
  '/caregiver/create': typeof CaregiverCreateRoute
  '/caregiver/ready': typeof CaregiverReadyRoute
  '/caregiver/record': typeof CaregiverRecordRoute
  '/caregiver/report': typeof CaregiverReportRoute
  '/senior/memories': typeof SeniorMemoriesRoute
  '/senior/record': typeof SeniorRecordRoute
  '/caregiver/home': typeof CaregiverHomeLazyRoute
  '/senior/home': typeof SeniorHomeLazyRoute
}

export interface FileRoutesByTo {
  '/caregiver/activity': typeof CaregiverActivityRoute
  '/caregiver/create': typeof CaregiverCreateRoute
  '/caregiver/ready': typeof CaregiverReadyRoute
  '/caregiver/record': typeof CaregiverRecordRoute
  '/caregiver/report': typeof CaregiverReportRoute
  '/senior/memories': typeof SeniorMemoriesRoute
  '/senior/record': typeof SeniorRecordRoute
  '/caregiver/home': typeof CaregiverHomeLazyRoute
  '/senior/home': typeof SeniorHomeLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/caregiver/activity': typeof CaregiverActivityRoute
  '/caregiver/create': typeof CaregiverCreateRoute
  '/caregiver/ready': typeof CaregiverReadyRoute
  '/caregiver/record': typeof CaregiverRecordRoute
  '/caregiver/report': typeof CaregiverReportRoute
  '/senior/memories': typeof SeniorMemoriesRoute
  '/senior/record': typeof SeniorRecordRoute
  '/caregiver/home': typeof CaregiverHomeLazyRoute
  '/senior/home': typeof SeniorHomeLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/caregiver/activity'
    | '/caregiver/create'
    | '/caregiver/ready'
    | '/caregiver/record'
    | '/caregiver/report'
    | '/senior/memories'
    | '/senior/record'
    | '/caregiver/home'
    | '/senior/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/caregiver/activity'
    | '/caregiver/create'
    | '/caregiver/ready'
    | '/caregiver/record'
    | '/caregiver/report'
    | '/senior/memories'
    | '/senior/record'
    | '/caregiver/home'
    | '/senior/home'
  id:
    | '__root__'
    | '/caregiver/activity'
    | '/caregiver/create'
    | '/caregiver/ready'
    | '/caregiver/record'
    | '/caregiver/report'
    | '/senior/memories'
    | '/senior/record'
    | '/caregiver/home'
    | '/senior/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  CaregiverActivityRoute: typeof CaregiverActivityRoute
  CaregiverCreateRoute: typeof CaregiverCreateRoute
  CaregiverReadyRoute: typeof CaregiverReadyRoute
  CaregiverRecordRoute: typeof CaregiverRecordRoute
  CaregiverReportRoute: typeof CaregiverReportRoute
  SeniorMemoriesRoute: typeof SeniorMemoriesRoute
  SeniorRecordRoute: typeof SeniorRecordRoute
  CaregiverHomeLazyRoute: typeof CaregiverHomeLazyRoute
  SeniorHomeLazyRoute: typeof SeniorHomeLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  CaregiverActivityRoute: CaregiverActivityRoute,
  CaregiverCreateRoute: CaregiverCreateRoute,
  CaregiverReadyRoute: CaregiverReadyRoute,
  CaregiverRecordRoute: CaregiverRecordRoute,
  CaregiverReportRoute: CaregiverReportRoute,
  SeniorMemoriesRoute: SeniorMemoriesRoute,
  SeniorRecordRoute: SeniorRecordRoute,
  CaregiverHomeLazyRoute: CaregiverHomeLazyRoute,
  SeniorHomeLazyRoute: SeniorHomeLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/caregiver/activity",
        "/caregiver/create",
        "/caregiver/ready",
        "/caregiver/record",
        "/caregiver/report",
        "/senior/memories",
        "/senior/record",
        "/caregiver/home",
        "/senior/home"
      ]
    },
    "/caregiver/activity": {
      "filePath": "caregiver.activity.tsx"
    },
    "/caregiver/create": {
      "filePath": "caregiver.create.tsx"
    },
    "/caregiver/ready": {
      "filePath": "caregiver.ready.tsx"
    },
    "/caregiver/record": {
      "filePath": "caregiver.record.tsx"
    },
    "/caregiver/report": {
      "filePath": "caregiver.report.tsx"
    },
    "/senior/memories": {
      "filePath": "senior.memories.tsx"
    },
    "/senior/record": {
      "filePath": "senior.record.tsx"
    },
    "/caregiver/home": {
      "filePath": "caregiver.home.lazy.tsx"
    },
    "/senior/home": {
      "filePath": "senior.home.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
